apiVersion: v1
kind: Secret
metadata:
  name: openim-mongo-secret
type: Opaque
data:
  mongo_openim_username: cm9vdA== # base64 for "root"
  mongo_openim_password: cm9vdDEyMzQ1Ng== # base64 for "root123456"
