apiVersion: v1
kind: Service
metadata:
  name: group-rpc-service
spec:
  selector:
    app: group-rpc-server
  ports:
    - name: grpc
      protocol: TCP
      port: 10260
      targetPort: 10260
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: group-rpc-prometheus
spec:
  selector:
    app: group-rpc-server
  ports:
    - name: prometheus-12260
      protocol: TCP
      port: 12260
      targetPort: 12260
  type: ClusterIP
