apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-rpc-server
  template:
    metadata:
      labels:
        app: auth-rpc-server
    spec:
      containers:
        - name: auth-rpc-server-container
          image: 10.88.88.13:81/app/openim-rpc-auth:v260131140326
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              value: "root123456"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10200
            - containerPort: 12200
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
