apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagegateway-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagegateway-rpc-server
  template:
    metadata:
      labels:
        app: messagegateway-rpc-server
    spec:
      containers:
        - name: openim-msggateway-container
          image: 10.88.88.13:81/app/openim-msggateway:v260202125441
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_USERNAME
              value: "root"
            - name: IMENV_MONGODB_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_ADDRESS
              value: "10.88.88.13:27017"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10140
            - containerPort: 12001
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
