apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: third-rpc-server
  template:
    metadata:
      labels:
        app: third-rpc-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: third-rpc-server-container
          image: 10.88.88.13:81/app/openim-rpc-third:v260202133850
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_MINIO_ACCESSKEYID
              value: "root"
            - name: IMENV_MINIO_SECRETACCESSKEY
              value: "root123456"
            - name: IMENV_REDIS_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_USERNAME
              value: "root"
            - name: IMENV_MONGODB_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_ADDRESS
              value: "10.88.88.13:27017"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10300
            - containerPort: 12300
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
