apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-rpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: third-rpc-server
  template:
    metadata:
      labels:
        app: third-rpc-server
    spec:
      containers:
        - name: third-rpc-server-container
          image: openim/openim-rpc-third:v3.8.3
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_MINIO_ACCESSKEYID
              value: "root"
            - name: IMENV_MINIO_SECRETACCESSKEY
              value: "root123456"
            - name: IMENV_REDIS_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_USERNAME
              value: "root"
            - name: IMENV_MONGODB_PASSWORD
              value: "root123456"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10300
            - containerPort: 12300
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
