apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rpc-server
  namespace: openim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-rpc-server
  template:
    metadata:
      labels:
        app: user-rpc-server
    spec:
      containers:
        - name: user-rpc-server-container
          image: 10.88.88.13:81/app/openim-rpc-user:v260202112947
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_USERNAME
              value: "root"
            - name: IMENV_MONGODB_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_ADDRESS
              value: "10.88.88.13:27017"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10320
            - containerPort: 12320
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
