apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversation-rpc-server
  template:
    metadata:
      labels:
        app: conversation-rpc-server
    spec:
      containers:
        - name: conversation-rpc-server-container
          image: 10.88.88.13:81/app/openim-rpc-conversation:v260202002538
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: DEPLOYMENT_TYPE
              value: "kubernetes"
            - name: IMENV_REDIS_PASSWORD
              value: "root123456"
            - name: IMENV_MONGODB_URI
              value: "mongodb://root:root123456@10.88.88.13:27017/openim_v3?authSource=admin"
            - name: MONGO_URI
              value: "mongodb://root:root123456@10.88.88.13:27017/openim_v3?authSource=admin"
            - name: MONGODB_URI
              value: "mongodb://root:root123456@10.88.88.13:27017/openim_v3?authSource=admin"
          volumeMounts:
            - name: openim-config
              mountPath: "/config"
              readOnly: true
          ports:
            - containerPort: 10220
            - containerPort: 12220
      volumes:
        - name: openim-config
          configMap:
            name: openim-config
