# Name of the bucket in MinIO
bucket: openim
# Access key ID for MinIO authentication
accessKeyID: root
# Secret access key for MinIO authentication
secretAccessKey: root123456
# Session token for MinIO authentication (optional)
sessionToken: 
# Internal address of the MinIO server
internalAddress: 10.88.88.13:9000
# External address of the MinIO server, accessible from outside. Supports both HTTP and HTTPS using a domain name
externalAddress: http://10.88.88.13:9000
# Flag to enable or disable public read access to the bucket
publicRead: false


